### PR TITLE
Give frames a sound when placed vertically

### LINKED ISSUE #1247: Placing Frame Box does not produce sound in some cases
### GregTech CEu Version

2.4.3-beta

### Modpack Used

_No response_

### Addons Installed

_No response_

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

Placing Frame Box on top of Frame Box or via stacking of frame boxes produces lock placement sound.

### Actual Behavior

No placement sound produced

### Steps to Reproduce

1) I placed Black Steel Frame Box
2) I placed Black Steel Frame Box on top of first one

### Additional Information

Block placement sound plays when placing Frame Box on ground. Or when placing it on side of Frame Box but main column does not have where to grow and Frame Box is placed on side.

### PR DESCRIPTION
**Pull request by DStrand1**
Closes #1247

Follows exact MC logic for sound. Taken from `net.minecraft.item.ItemBlock.class`:
```
if (placeBlockAt(itemstack, player, worldIn, pos, facing, hitX, hitY, hitZ, iblockstate1))
{
    iblockstate1 = worldIn.getBlockState(pos);
    SoundType soundtype = iblockstate1.getBlock().getSoundType(iblockstate1, worldIn, pos, player);
    worldIn.playSound(player, pos, soundtype.getPlaceSound(), SoundCategory.BLOCKS, (soundtype.getVolume() + 1.0F) / 2.0F, soundtype.getPitch() * 0.8F);
    itemstack.shrink(1);
}
```

### CODE REVIEW

**Comment by LAGIdiot** [comment]
Sound plays, which is nice. Though I don't think it is correct sound as when placing Titanium Frame on Wooden Frame it plays wood sound and placing Titanium Frame on Titanium Frame it plays metal sound.  Also sound is always played at position player clicks not position where block is placed.

**Comment by brachy84** [comment]
Does it work for framed pipes

**Comment by LAGIdiot** [comment]
I have tested with framed pipes just now and placing Pipe in existing Frame Box **does** play sound. Placing Frame Box on existing Frame Box containing Pipe **does** play sound. Placing Frame Box on existing Pipe **does not**. So @DStrand1 if you can look at that problem too.

**Comment by LAGIdiot** [comment]
I can confirm tat last commit fixed sounds when placing Frame Box on existing Pipe,

**Review by LAGIdiot — APPROVED** [review]
This fix is good enough for me, though it is not perfect.

**Pull request merged**
