### PR TITLE
Give proper credits in README

### LINKED ISSUE #851: [BUG] Readme forgot to credit many things
**Describe the bug**
"Credit Works" section of the [README.md](https://github.com/GregTechCEu/GregTech#readme) forgot to credit so many things

- Auto-maintenance Hatch is from TecTech (stated in the Community Pack)
- hardmode vanilla recipes and EBF recipe are from GT:NH
- World Accelerator is [from GT:NH](https://github.com/GTNewHorizons/GTplusplus/commit/e2d1aeed445090567cb84057a1f09098ae4f7c5f)
- Potin Fluid Pipe is from GT++ (stated in the Community Pack)
- Extreme Combustion Engine is from GT:NH (stated in the Community Pack)
- Certificate of Not Being a Noob Anymore is from Crops++
- Clipboard is from BiblioCraft
- Empty Wooden Form and Brick Wooden form is from GT:NH(Wooden Brick form)
- Energy Hatch Coil textures are from GT:NH
- GUI of the Super Tanks is from IMPACT

also there is a miscredit

> Primitive Water Pump is from the [Impact: GregTech Edition Modpack](https://gtimpact.space/).

should be

> Primitive Water Pump is from the [IMPACT: GREGTECH EDITION Modpack](https://gtimpact.space/).

I may have mistaken or forgotten something 😐 
feel free to point it out

**Versions**
[5dc1d34](https://github.com/GregTechCEu/GregTech/commit/5dc1d34d14f88b44438ddf339e097fec7a539e6e)

### PR DESCRIPTION
**Pull request by Quarri6343**
**Outcome:**
Fix #851

### CODE REVIEW

**Comment by GlodBlock** [comment]
`World Accelerator` is added by gt++ tho

**Comment by Quarri6343** [comment]
> `World Accelerator` is added by gt++ tho

Someone told me that World Accelerator is added by GT:NH
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/b39c73c17b06ff0d3d9178cbe5ac50cff9a85d27
than gt++ ported it
https://github.com/GTNewHorizons/GTplusplus/commit/e2d1aeed445090567cb84057a1f09098ae4f7c5f
image

**Comment by GlodBlock** [comment]
ah, my bad. don't notice that port

**Comment by TechLord22** [comment]
Superseded by [6e0d7a0](https://github.com/GregTechCEu/GregTech/commit/6e0d7a06dac1f083f2ce8515db830990fa7d2919).

**Pull request closed without merging**
