### PR TITLE
Fix groovyscript server crash

### PR DESCRIPTION
**Pull request by serenibyss**
More strictly marks things with `@SideOnly(Side.CLIENT)`

### CODE REVIEW

**Comment by ALongStringOfNumbers** [comment]
Still crashing in GCP with this jar when attempting to start a server. Log here: https://gist.github.com/ALongStringOfNumbers/8a62aa8ccd6509a763c7bfb450aeaa87

**Comment by brachy84** [comment]
I also still got that error. With my commit and the classload-fix branch for grs it works.

**Comment by ALongStringOfNumbers** [comment]
Ok, so with the most recent commit and the GS class fix branch, I can successfully boot the server up. However, I am encountering this error about the greenhouse in the log when I do so https://pastebin.com/Ng2Pmdcw, would this error be because of the changes in the GS branch, or would it be on the pack's end?

There are also a couple other GS related errors in the log, https://pastebin.com/bGNM3P3m, which I am not sure if are related to the previous error, or any of the changes made in GS or this PR.

**Comment by Irgendwer01** [comment]
> Ok, so with the most recent commit and the GS class fix branch, I can successfully boot the server up. However, I am encountering this error about the greenhouse in the log when I do so https://pastebin.com/Ng2Pmdcw, would this error be because of the changes in the GS branch, or would it be on the pack's end?
> 
> There are also a couple other GS related errors in the log, https://pastebin.com/bGNM3P3m, which I am not sure if are related to the previous error, or any of the changes made in GS or this PR.

@ALongStringOfNumbers Overriding the `getPaintingColorForRendering` method in the Greenhouse class fixed the issue for me

**Comment by brachy84** [comment]
God i hate this

**Comment by brachy84** [comment]
The first error means that the mte class failed to load, but for some reason it doesnt log the error. The latest commit on the grs branch fixes that.
The second issue just means that the recipe map does not exist because it's created the mte class, which failed to load.

**Review by ALongStringOfNumbers — APPROVED** [review]

**Pull request merged**
