### PR TITLE
GroovyScript 1.1.0 

### PR DESCRIPTION
**Pull request by brachy84**
## What
Update GroovyScript to 1.1.0. GregTech is currently still compatible with 1.1.0, but its using some deprecated methods. GT will be incompatible with 1.2.0 (without this pr). Additionaly now an error is logged when people try to use the old material components method.

## Implementation Details
java

## Outcome
Future compatibility with GrS 1.2.0 and minor improvements

## Additional Information
Hi

## Potential Compatibility Issues
None

### CODE REVIEW

**Comment by ALongStringOfNumbers** [comment]
This currently crashes if groovyscript is not installed with this error https://pastebin.com/fXpVHy78

Also, are any of these new classes you are extending introduced in 1.1.0? If so, we would also need to bump the minimum version in GregTechMod

**Comment by ALongStringOfNumbers** [comment]
When loading into a world with gs 1.1.0-hotifx nad this version on CEu, then leaving the world and loading in with GS disabled, the following missing item warning is displayed <https://pastebin.com/VgTzQ1M1>

Is this intended, and why placeholder as the mod name in the resource location?

**Comment by brachy84** [comment]
:concern: that doesnt look right

**Comment by brachy84** [comment]
Yes thats intended. GrS now automatically adds its own material registry with the pack id which is defined in the groovy run config. `placeholdername` is the default value

**Review by ALongStringOfNumbers — APPROVED** [review]

**Pull request merged**
