### PR TITLE
Change Bender Recipe

### PR DESCRIPTION
**Pull request by IntegerLimit**
## What
Replaces the Bender Recipe. The new recipe requires no wrench, and is shown in the screenshot below. Many people complained about how a wrench in the recipe was very annoying, especially later in the game.
Further discussion and consideration might want to be taken on the new recipe. 

Furthermore, adds Double Plates as a crafting component, for further expansion on machine making.

## Outcome
Removes the need for a wrench in the recipe. This is consistent with all the other machines.

## Potential Compatibility Issues
People will need to change their AE2 patterns.
Maybe some very specific CT/Groovy scripts will break?

### CODE REVIEW

**Review by LAGIdiot — COMMENTED** [review]
I understand reasoning behind this change and I support it. Regarding use item it seems bit strange to use just single plate maybe double plate would be better? Sure you would need to craft first one with just tools as you can't produce it automated way without Bender itself, but I don't expect that being problem.

**Comment by IntegerLimit** [comment]
Ok, I'll change it to a double plate, that made more sense for me as well, but Tech said in Discord that it might be too expensive.

**Comment by IntegerLimit** [comment]
Should I make this a config? Config off = plate, config on = double plate, or is it okay?

**Comment by ghzdude** [comment]
Personally, I don't think a config is necessary, as you only need to make the bending machine once to easily make plates and double plates.

**Comment by IntegerLimit** [comment]
Okay.

**Review by LAGIdiot — APPROVED** [review]
I think this is better. Thank you for finishing the PR.

**Comment by IntegerLimit** [comment]
Updated this branch with changes on master.

**Comment by TechLord22** [comment]
After further discussion, we determined that a single plate is better for this recipe. It is likely new players will see the double plate, which is very similar in appearance to the single plate, and mistake it for one. They would then attempt to use a single plate, and it will cause them significant confusion when the recipe does not work. This change was made in 048a9c7.

Additionally, at some point in the future there is some likelihood we remove the double plate manual crafting recipe, in order to make it a higher tier unlock (as it currently needs an MV bending machine for automation).

**Pull request merged**
