### PR TITLE
Add colorful lamps

### PR DESCRIPTION
**Pull request by Zalgo239**
## What
Adds colorful redstone sensitive lamps to the game. They are on by default and can be deactivated with a redstone signal.

## Implementation Details
Added two blocks for the on/off lamps, with 16 variants each, one per color. When the block is updated it checks if it is being powered and swaps itself with the active/inactive block when necessary.
The inactive block is not normally obtainable as an item in survival.

## Outcome
We now have colored lamps (they look nice).

## Additional Information
On
Off

### CODE REVIEW

**Comment by ALongStringOfNumbers** [comment]
Instead of two different blocks, these could probably be VariantActiveBlocks after #1168

**Comment by brachy84** [comment]
> Depending on how long that will take it might be worth waiting for it or just merging and then reworking this.
But then you have to worry about backwards compat

**Comment by Zalgo239** [comment]
> But then you have to worry about backwards compat

Just been told that PR is almost ready, so I just labelled this as do not merge. I'll be rebasing once #1168 is merged.

**Comment by LAGIdiot** [comment]
@Zalgo239 PR you were waiting for is already merged.

**Comment by ALongStringOfNumbers** [comment]
Superseded by #1635

**Pull request closed without merging**
