### PR TITLE
 port some of GCP quests into Item Guide App

### PR DESCRIPTION
**Pull request by Quarri6343**
**What:**
I'm maintaining a released modpack and many people ask me about basic questions about GTCEu.
That's because... GTCEu has no in-game manual although 4 months have passed since the initial release!
#506 appearently takes forever to finish since the UI rework is delaying, so I decided to paste community pack quests into Guide App very quickly

I only put important quests into the guide app
Because I guess nobody wants to see a sugar cane gathering quest in the guide app...
If I have time, I'll consider porting some less important quests such as oxygen in the future PR

This is the first part of quest porting PRs, there will be Multiblock Guide and Machine Guide version soon™

**Implementation Details:**
<details>
<summary>ITEM LIST</summary>

- axe
- hammer
- bucket
- important tools
- mining hammer
- more tools
- terminal
- covers_behaviour
- drills
- electric_prospectors_scanner(LV)
- empty_cell
- fluid_regulator
- low_voltage_item_magnet
- lv_conveyor_module
- lv_electric_piston
- lv_electric_pump
- lv_robot_arm
- small_sodium_battery
- spray_can
- voiding_covers
- electric_thruster_jetpack
- large_cell
- liquid_fueled_impeller_jetpack
- medium_sodium_battery
- mv_components
- portable_scanner
- smart_item_filter
- auto_build(terminal item function)
- digital_interface_cover
- energium_crystal
- hv_components
- hv_prospector
- infinite_water_cover
- nanomuscle_suite
- ore_dictionary_filter
- advanced_nanomuscle
- ender_fluid_link_cover
- ev_components
- lapotron_crystal
- lapotronic_energy_orb

</details>

**Outcome:**
GTCEu becomes more beginner friendly

**Additional info:**
preview of the new guide app
キャプチャ1289
acknowledgement from Dan
キャプチャ1290

**Possible compatibility issue:**
conflicts with #506 
this is a temporal solution so #506 should override this

### CODE REVIEW

**Comment by brachy84** [comment]
Nice, but maybe categorize it a little different. For example covers, tools armor... etc

**Comment by Quarri6343** [comment]
hmm
GCP categorizes them with tiers and also has quest descriptions based on tiers
so if I recategorize them with types the quest descriptions will be a mess imo
@brachy84 may I ask you why categorizing with types is better?

**Comment by brachy84** [comment]
because it's not a fucking questbook and it will be easier to find shit

**Comment by Quarri6343** [comment]
`give an example`
currently guide app forces alphabetical order
so if I put motor quests in the same group it will be ordered to EV motor -> HV motor-> LV motor -> MV motor,
unless I rename all of them manually
if I do it to every quests it will be hard to do any change to them
(and I don't want to spend much time to this project since it is a kind of placeholder)

another example: smart item filter is assosiated with MV Electrolyzer strongly although it is not mentioned in the quest,
and Ore Dictionary filter is linked with Vacuum Freezer (HV)
they should be categorized with voltage instead of type to avoid confuse

hold on. I will ask Syrcan
he is the author so his opinion is important

**Comment by Quarri6343** [comment]
In this rework,

- I changed the categorization as @brachy84 said
キャプチャ1294

- deleted some placeholder empty quests which was added in the #506 because it makes people difficult to search in the terminal

- deleted some GCP quests because the corresponding guides are already added in #506

- deleted lv piston quest

**Pull request closed without merging**
