### PR TITLE
Pipe rework

### PR DESCRIPTION
**Pull request by lordclips**
## What
Rework pipes to be somewhat more efficient and generic

## Implementation Details
HAHAHAHAAHA. Ask me on Discord, you'll get a generally better idea of what they're supposed to be. Details will also be provided as work is done.

## Outcome
Pipe networks that are more generic and applicable to different molds, allowing for greater extensibility for networks of many different types (Fluid, Item, Energy, Rotation, etc etc).

## Potential Compatibility Issues
I genuinely cannot tell how much this will affect, but from what I've been told, this change is far from a little breaking.

### CODE REVIEW

**Comment by lordclips** [comment]
Currently: Pipes and all references to them literally do not exist outside of recipes. To get this PR to launch (if you would ever subject yourself to such a thing), consider the following:

1. Go to GregTechMod.java
2. Go to onInit
3. Remove `|| !FMLForgePlugin.RUNTIME_DEOBF`
4. Game will launch

It's probably not a good or practical way to do such a thing, but my goal was to literally kill everything and get the game to launch, and recipes were stopping the launch part, and doing that fixes the recipes stopping the launch part.

**Comment by LAGIdiot** [comment]
I don't think it was great idea to start by nuking all of pipe code. As you will need to run two instance of game to compare functionality, behavior and other things. Also making compatibility fixes later will be way harder as right now you don't have any reference to current system.

**Comment by lordclips** [comment]
I'll deal with the reference pains. I couldn't reasonably grapple with the hell that was the old system and a nuke was the only semi-reasonable way I could, for myself, build a new system. I'll deal with stuff such as compat, fixes, etc later down the road once the main logic is built. Ill take some hardship later if it means not having to deal with some of the uh, cursed shit I saw.

**Comment by lordclips** [comment]
Rebasing this shit to be up to date was hell

**Comment by ALongStringOfNumbers** [comment]
Going to close this as it has large amount of conflicts, and has not been worked on in a while. If this is still desired, it might be better to fully flesh out locally first.

**Pull request closed without merging**
