### PR TITLE
Recipe conflict detection

### PR DESCRIPTION
**Pull request by kumquat-ir**
**What:**
Adds a command to check all Recipes in all RecipeMaps to see if anything seems to conflict with them.

**How solved:**
Iterate over all recipes in each map, and for each one:
* Generate a list of inputs that has 100x the number of items and 10000x the amount of fluid as usual
* Use `RecipeMap.findRecipe` on the input list
* Check if the recipe object returned is the same as the input recipe object

Afterwards, pretty-print all detected conflicts to the log.

**Outcome:**
Less recipe conflicts

**Additional info:**
Example conflict messages:
```
In map arc_furnace
Tried: EU/t: 30, Duration: 3312
Item inputs:
    { gregtech:meta_block_compressed_26 * 1 (Meta 15) } * 1
Fluid inputs:
    material.oxygen * 3312
Item outputs:
    gregtech:meta_block_compressed_26 * 1 (Meta 15)

Found: EU/t: 30, Duration: 368
Item inputs:
    { gregtech:meta_block_compressed_26 * 1 (Meta 15) } * 1
Fluid inputs:
    material.oxygen * 368
Item outputs:
    (MetaItem) OrePrefix: ingot, Material: enriched_naquadah_trinium_europium_duranide
```

(There unfortunately does not seem to be a good way to get the oredict name from the `CountableIngredient`)
```
In map assembler
Tried: EU/t: 4, Duration: 300
Item inputs:
    { minecraft:planks * 1 (Meta 3) } * 1
    { Config circuit #3 } * 0
Item outputs:
    minecraft:jungle_fence * 1 (Meta 0)

Found: EU/t: 4, Duration: 300
Item inputs:
    (OreDict) { minecraft:planks * 1 (Meta 0) minecraft:planks * 1 (Meta 1) minecraft:planks * 1 (Meta 2) minecraft:planks * 1 (Meta 3) minecraft:planks * 1 (Meta 4) minecraft:planks * 1 (Meta 5) gregtech:planks * 1 (Meta 0) (MetaItem) OrePrefix: plate, Material: wood } * 3
    { Config circuit #3 } * 0
Item outputs:
    minecraft:trapdoor * 2 (Meta 0)
```

```
In map macerator
Tried: EU/t: 2, Duration: 98
Item inputs:
    { } * 1
Item outputs:
    (MetaItem) OrePrefix: dust, Material: paper

Found: null (Is something else going wrong?)
```
**Possible compatibility issue:**
Will not detect conflicts only present when extra items are required to present the conflict, or conflicts that just happen to produce the correct recipe and do not occur when running the conflicting recipe due to extra inputs

### CODE REVIEW

**Comment by brachy84** [comment]
this will conflict with #504 where i removed the `util` part of the command

**Comment by kumquat-ir** [comment]
Due to the difficulty of bootstrapping the test environment to a point where all our recipes have been registered, the ci test will unfortunately not be happening in this PR.  Someone else can feel free to try to implement it.

**Comment by kumquat-ir** [comment]
This is basically done, but the recipe matching code will most likely will need to be redone for #329 and #530.
Could refactor the pretty-printing stuff into its own class, if we want them for other places.

Current list of recipe conflicts detected, for reference (in the order they are printed in the log):
* Duplicate recipes for glowstone plates in cutter
* Duplicate recipes for coke bricks in alloy smelter
* Duplicate recipes for glowstone blocks in fluid solidifier
* Redstone block and plate conflict in compressor
* Arc furnacing polymer block conflicts with outputs of either ash or 9 ingots
* Arc furnacing non-polymer block conflicts with outputs of either the block itself or 9 ingots
* Some macerator recipe with no inputs outputting 3 chad
* Duplicate recipes for wheat dust in macerator
* Conflict between large steel cell and normal cell in extruder
* Conflict between wood stairs and doors in assembler (config 6)
* Conflict between stone wall and stairs in assembler (config 6)
* Conflict between wood fence and trapdoors in assembler (config 3)

All recipe configs are on their default values, there may be more on other config combinations

**Review by DStrand1 — APPROVED** [review]

**Comment by Vliro** [comment]
In #530 all recipes are stored as a Collection<Recipe>, so if at any leaf size() > 1 you get a conflict (it simply means the same input can react multiple recipes) You can supply a predicate simply being a -> true and it won't check ingredient counts.

**Pull request merged**
