### PR TITLE
Added a overridable minumum time in ticks for the pattern checker to run

### PR DESCRIPTION
**Pull request by YoungOnionMC**
**What:**
Adding a customizable wait time for multiblocks to do structure checks, rather than just each second.

**How solved:**
Made an overridable method for changing the minimum number of ticks before it runs the structure check.

### CODE REVIEW

**Comment by Syrcan** [comment]
Why "minimum" in the name? That sounds confusing.
`getPatternCheckFrequency()` sounds more accurate to what it does.

**Comment by YoungOnionMC** [comment]
getOffsetTimer() already has a random, (0, 20] ticks, that it waits to do the check, so this would be the base minimum ticks it waits.

**Comment by Syrcan** [comment]
`getOffsetTimer()` exists to prevent MTEs from running their "once per second" checks all at the same time. It distributes ticks more evenly to avoid having spikes.
The only randomness from `getOffsetTimer()` is when the MTE gets loaded in the world, but after that it is consistent.
`getOffsetTimer() % 20` returns true exactly once per second, there is no minimum.

**Comment by brachy84** [comment]
This feels unecessary since pattern checking is already spread over multiple ticks

**Comment by YoungOnionMC** [comment]
this is to make the absolute minimum before each structure check happen over seconds or minutes, not just every second(somewhere in the second)

**Comment by LAGIdiot** [comment]
I don't feel like this is needed, given that it was not touched for 10 months. So I propose to close it.

**Pull request closed without merging**
