### PR TITLE
align lang format，Completely Sinicized

### PR DESCRIPTION
**Pull request by sakuranosakana**
English：Slightly optimized the format, adjusted the wrong position, and provided Sinicization for the clean room
Chinese：略微优化格式，调整了错误的位置，为超净间提供汉化

### CODE REVIEW

**Comment by Quaerere-Git** [comment]
Maybe fix the translation of Trinaquadalloy?

**Comment by Quarri6343** [comment]
Could you merge #1315 into this PR so we can begin comparing with #1309 ?

**Comment by sakuranosakana** [comment]
> Could you merge #1315 into this PR so we can begin comparing with #1309 ?

Completion of merger  #1740 already has that translation

**Comment by TechLord22** [comment]
With the merge of #1309, we think it best to have translations start from a clean slate in order to minimize conflicts and improve accuracy of translation. Therefore, I am closing this PR. 

Please create a new Pull Request with changes compatible with the current state of the zh_cn translation.

**Pull request closed without merging**
