### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rentommy**
zh_ch.lang
Line 4210
Translation correction

### CODE REVIEW

**Comment by Quaerere-Git** [comment]
I think it can be more colloquial.

**Comment by rentommy** [comment]
If it is'至高的 OP 请削弱‘the meaning of 'OP' may be mistranslated.
If you want to be more colloquial you can change it to ‘太阳能太强大了把它削弱一下’.

**Comment by Quaerere-Git** [comment]
> If it is'至高的 OP 请削弱‘the meaning of 'OP' may be mistranslated. If you want to be more colloquial you can change it to ‘太阳能太强大了把它削弱一下’.

Maybe a bit shorter?

**Comment by rentommy** [comment]
太阳能太强大了请削弱？

**Comment by TechLord22** [comment]
With the merge of https://github.com/GregTechCEu/GregTech/pull/1309, we think it best to have translations start from a clean slate in order to minimize conflicts and improve accuracy of translation. Therefore, I am closing this PR.

Please create a new Pull Request with changes compatible with the current state of the zh_cn translation.

**Pull request closed without merging**
