### PR TITLE
More translations, and adapt to the next Release

### PR DESCRIPTION
**Pull request by KasumiNova**
**What:**
_More translations, and adapt to the next Release, just like the last PR._

**Implementation Details:**
_Organize zh_cn.lang content._

**Outcome:**
_More zh_cn translations._

### CODE REVIEW

**Comment by Quarri6343** [comment]
"umv" became "uxv" and "uxv" became "opv" in the latest en_us.lang so you probably want to change them

**Comment by KasumiNova** [comment]
The translation and conversion of "umv" to "uxv" and "uxv" to "opv" have been completed

**Comment by Quarri6343** [comment]
you may also want to change every machine tooltips format from this
https://github.com/GregTechCEu/GregTech/blob/8a906b6fd1d235e1e5bfc353043e88072ec2094c/src/main/resources/assets/gregtech/lang/zh_cn.lang#L3163-L3177
to this
https://github.com/GregTechCEu/GregTech/blob/94d53ab0fa0d2123c0e573a0279c82b0eb2ee99b/src/main/resources/assets/gregtech/lang/en_us.lang#L3481-L3507
to adapt to the next release

**Comment by KasumiNova** [comment]
It looks like it will take a while, I'll try to work on it as much as I can

**Comment by KasumiNova** [comment]
Finished translating after the UV adaptation phase and fixed the tooltip

**Review by TechLord22 — APPROVED** [review]

**Pull request merged**
