### PR TITLE
Update Dev Cape Registry

### PR DESCRIPTION
**Pull request by Quarri6343**
## What
Many people have joined GTCEu dev team since 2021 so I updated the dev cape registry

## Implementation Details
I added following people
https://namemc.com/profile/htmlcsjs.1
https://namemc.com/profile/PrototypeTrouser.1
https://namemc.com/profile/Quarri6343.1
https://namemc.com/profile/LAGIdiot.1
https://namemc.com/profile/Tictim.1

## Outcome
Devs will be happy

### CODE REVIEW

**Comment by bruberu** [comment]
One important question, in order to optimize how happy the developer team is, is if we want to sync these capes up with exactly who has the 1.12 Developer role on the GTCEu discord (which includes Exa and BraggestSage833). The implementation itself is fine.

**Comment by Quarri6343** [comment]
oops, I forgot about them because there are only 12 people in GitHub repo...
キャプチャ1985
I'll ask Exa his MCID first

**Comment by Quarri6343** [comment]
I added following people
https://namemc.com/profile/BraggestSage833.1
https://namemc.com/profile/Exaxxion4096.1

**Review by bruberu — APPROVED** [review]
Thank you for taking that into consideration. This should be fine to merge now.

**Pull request merged**
