### PR TITLE
No more scanner

### PR DESCRIPTION
**Pull request by kumquat-ir**
**What:**
Removes the Scanner item and makes surface rocks not TileEntities

**How solved:**
deleted lots of code

**Outcome:**
Scanner has been replaced with LV Prospector in terminal hardware
ID shifts clipboard, terminal, prospectors down 1
All surface rocks are now made of aluminium - fix in block model gen pr, or somewhere else?
Removing ore materials no longer bricks worlds
Cherry-picked tenorite/cuprite removal since now it will not brick worlds
Renamed surface rock rendering classes to something less confusing

**Possible compatibility issue:**
When loading old worlds, the log is spammed with `[Server thread/WARN] [minecraft/TileEntity]: Skipping BlockEntity with id gregtech:surface_rock`

### CODE REVIEW

**Review by Yefancy — APPROVED** [review]

**Comment by Rongmario** [comment]
Could you explain what you meant by `Cherry-picked tenorite/cuprite removal since now it will not brick worlds`?

The compatibility issue is fine since no one should be using it in existing worlds anyway, and even if that does happen; the log is only spammed with that on first load. (assuming all chunks containing remnants of surface rocks are loaded)

LGTM otherwise.

**Comment by ALongStringOfNumbers** [comment]
> Could you explain what you meant by `Cherry-picked tenorite/cuprite removal since now it will not brick worlds`?
> 
> The compatibility issue is fine since no one should be using it in existing worlds anyway, and even if that does happen; the log is only spammed with that on first load. (assuming all chunks containing remnants of surface rocks are loaded)

It was briefly used on existing worlds when the commit made it to the testing server, where the vein removal caused a crash, and so the commit had to be reverted

**Comment by Rongmario** [comment]
> > Could you explain what you meant by `Cherry-picked tenorite/cuprite removal since now it will not brick worlds`?
> > The compatibility issue is fine since no one should be using it in existing worlds anyway, and even if that does happen; the log is only spammed with that on first load. (assuming all chunks containing remnants of surface rocks are loaded)
> 
> It was briefly used on existing worlds when the commit made it to the testing server, where the vein removal caused a crash, and so the commit had to be reverted

Gotcha!

**Review by ALongStringOfNumbers — COMMENTED** [review]
Could you also delete the scanner lang entries and the scanner model and texture files?

**Review by ALongStringOfNumbers — APPROVED** [review]

**Review by TechLord22 — APPROVED** [review]

**Pull request merged**
